model_name: google_genai:gemini-2.5-flash

input_folder: devset/PT/subtask-2-documents/
output_file: results/devset/gemini25_flash_no_val/pt_dev_results.txt
enable_validation: false
enable_narrative_validation: false
enable_subnarrative_validation: false
enable_cleaning: true
max_concurrency: 20