# Multi-Agent Classification Configuration - OpenAI GPT-5 Nano English Narrative Majority Vote (3 Agents)
model_name: "openai:gpt-5-nano"
input_folder: "testset/EN/subtask-2-documents/"
output_file: "results/{model_name}/en_narrative_majority_3agents.txt"

# Multi-agent settings
num_narrative_agents: 3  # Number of agents for narrative classification
num_subnarrative_agents: 1 # Number of agents for subnarrative classification
aggregation_method: "majority"  # Options: "union", "intersection", or "majority"

# Standard settings
enable_validation: false
enable_cleaning: true
enable_text_cleaning: false
max_concurrency: 15
