model_name: google_genai:gemini-2.5-pro

input_folder: testset/HI/subtask-2-documents/
output_file: results/gemini25_pro/hi_results.txt
enable_validation: false
enable_cleaning: true
max_concurrency: 10