model_name: google_genai:gemini-2.5-flash-lite

input_folder: testset/EN/subtask-2-documents/
output_file: results/gemini_mixed/en_results.txt
enable_validation: true
enable_cleaning: true
max_concurrency: 15

# Per-node model overrides
category:
  classification:
    model: google_genai:gemini-2.5-flash-lite
  validation:
    model: google_genai:gemini-2.5-flash

narratives:
  classification:
    model: google_genai:gemini-2.5-flash-lite
  validation:
    model: google_genai:gemini-2.5-flash

subnarratives:
  classification:
    model: google_genai:gemini-2.5-flash-lite
  validation:
    model: google_genai:gemini-2.5-flash