model_name: openai:gpt-5-nano
input_folder: testset/EN/subtask-2-documents/
output_file: results/experiment_gpt5nano_validation_only.txt
enable_validation: true
enable_cleaning: false
max_concurrency: 20
