model_name: openai:gpt-5-nano  # Default model for all nodes

input_folder: testset/EN/subtask-2-documents/
output_file: results/{model_name}/experiment_mixed_models.txt
enable_validation: true
enable_cleaning: true
max_concurrency: 20

# Optional per-node model overrides
category:
  classification:
    model: openai:gpt-5-nano  # Use same model for category classification
  validation:
    model: openai:gpt-5-nano  # Use same model for validation

narratives:
  classification:
    model: openai:gpt-5-nano  # Use gpt-5-nano for narrative classification
  validation:
    model: openai:gpt-5-nano  # Use gpt-5-nano for validation

subnarratives:
  classification:
    model: openai:gpt-5-nano  # Use gpt-5-nano for subnarrative classification
  validation:
    model: openai:gpt-5-nano  # Use gpt-5-nano for validation
