# Multi-Agent Classification Configuration - OpenAI GPT-5 Nano Russian Full Union
model_name: "openai:gpt-5-nano"
input_folder: "testset/RU/subtask-2-documents/"
output_file: "results/{model_name}/ru_full_union.txt"

# Multi-agent settings
num_narrative_agents: 2  # Number of agents for narrative classification
num_subnarrative_agents: 2 # Number of agents for subnarrative classification
aggregation_method: "union"  # Options: "union" or "intersection"

# Standard settings
enable_validation: false
enable_cleaning: true
enable_text_cleaning: false
max_concurrency: 10
